// Getters
export const TODOS = "TODOS";
export const GET_TODO_BY_ID = "GET_TODO_BY_ID";
export const GET_TODO = "GET_TODO";
export const GET_FILTERED_TODOS = "GET_FILTERED_TODOS";
export const GET_ACTIVE_FILTER = "GET_ACTIVE_FILTER";

// Mutations
export const MUTATE_ADD_TODO = "MUTATE_ADD_TODO";
export const MUTATE_UPDATE_TODO = "MUTATE_UPDATE_TODO";
export const MUTATE_REMOVE_TODO = "MUTATE_REMOVE_TODO";
export const MUTATE_CHANGE_FILTER = "MUTATE_CHANGE_FILTER";
export const MUTATE_CLEAR_COMPLETED = "MUTATE_CLEAR_COMPLETED";
export const MUTATE_MARK_ALL_COMPLETED = "MUTATE_MARK_ALL_COMPLETED";

// Actions
export const ACTIONS_ADD_TODO = "ACTIONS_ADD_TODO";
export const ACTIONS_UPDATE_TODO = "ACTIONS_UPDATE_TODO";
export const ACTIONS_REMOVE_TODO = "ACTIONS_REMOVE_TODO";
export const ACTIONS_CHANGE_FILTER = "ACTIONS_CHANGE_FILTER";
export const ACTIONS_CLEAR_COMPLETED = "ACTIONS_CLEAR_COMPLETED";
export const ACTIONS_MARK_ALL_COMPLETED = "ACTIONS_MARK_ALL_COMPLETED";
